# Generated by Django 5.2.8 on 2025-11-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('data_aquisicao', models.DateField()),
                ('status', models.CharField(choices=[('Em Uso', 'Em Uso'), ('Estoque', 'Estoque'), ('Manutenção', 'Manutenção')], default='Estoque', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.categoria')),
            ],
        ),
    ]
